/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as WalletRouteImport } from "./routes/wallet"
import { Route as NotFoundRouteImport } from "./routes/not-found"
import { Route as CallbackRouteImport } from "./routes/callback"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as WalletAddTokenRouteImport } from "./routes/wallet.add-token"

const WalletRoute = WalletRouteImport.update({
  id: "/wallet",
  path: "/wallet",
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: "/not-found",
  path: "/not-found",
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: "/callback",
  path: "/callback",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const WalletAddTokenRoute = WalletAddTokenRouteImport.update({
  id: "/add-token",
  path: "/add-token",
  getParentRoute: () => WalletRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/callback": typeof CallbackRoute
  "/not-found": typeof NotFoundRoute
  "/wallet": typeof WalletRouteWithChildren
  "/wallet/add-token": typeof WalletAddTokenRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/callback": typeof CallbackRoute
  "/not-found": typeof NotFoundRoute
  "/wallet": typeof WalletRouteWithChildren
  "/wallet/add-token": typeof WalletAddTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/callback": typeof CallbackRoute
  "/not-found": typeof NotFoundRoute
  "/wallet": typeof WalletRouteWithChildren
  "/wallet/add-token": typeof WalletAddTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/callback" | "/not-found" | "/wallet" | "/wallet/add-token"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/callback" | "/not-found" | "/wallet" | "/wallet/add-token"
  id:
    | "__root__"
    | "/"
    | "/callback"
    | "/not-found"
    | "/wallet"
    | "/wallet/add-token"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  NotFoundRoute: typeof NotFoundRoute
  WalletRoute: typeof WalletRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/wallet": {
      id: "/wallet"
      path: "/wallet"
      fullPath: "/wallet"
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/not-found": {
      id: "/not-found"
      path: "/not-found"
      fullPath: "/not-found"
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/callback": {
      id: "/callback"
      path: "/callback"
      fullPath: "/callback"
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/wallet/add-token": {
      id: "/wallet/add-token"
      path: "/add-token"
      fullPath: "/wallet/add-token"
      preLoaderRoute: typeof WalletAddTokenRouteImport
      parentRoute: typeof WalletRoute
    }
  }
}

interface WalletRouteChildren {
  WalletAddTokenRoute: typeof WalletAddTokenRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletAddTokenRoute: WalletAddTokenRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  NotFoundRoute: NotFoundRoute,
  WalletRoute: WalletRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
